version: '3.8'
services:
  inventory:
    build: ./service-inventory
    ports:
      - "8081:8081"
  billing:
    build: ./service-billing
    ports:
      - "8082:8082"
    depends_on:
      - inventory
  frontend:
    build: ./frontend-angular
    ports:
      - "4200:80"
    depends_on:
      - billing
      - inventory
